# Spring Boot application configuration file
server.port=8080
server.ssl.enabled=true
server.ssl.key-store=classpath:generate_another_keystore.p12
server.ssl.key-store-password=
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=

# Spring Data MongoDB configuration
spring.application.name=
spring.data.mongodb.uri=
spring.data.mongodb.database=
spring.data.mongodb.auto-index-creation=true

# Spring Security configuration
app.security.jwt.secret=
app.security.jwt.expiration=

# Spring Boot Actuator configuration
rate-limit.enabled=true
rate-limit.request-per-second=10

# Spring Doc configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html